# Generated by Django 3.1.2 on 2020-12-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animeval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_title', models.CharField(max_length=100)),
                ('review_title', models.CharField(max_length=50)),
                ('review_content', models.TextField()),
                ('evaluation_value', models.CharField(max_length=9)),
                ('evaluation_value_ave', models.PositiveIntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='username',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='specialized_field',
            new_name='favarite_anime',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='self_introduction',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='univ_name',
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeval.profilemodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
